curso_symfony_main_homepage:
    path:     /hello/{name}
    defaults: { _controller: CursoSymfonyMainBundle:Default:index }

curso_symfony_main_help:
    path:     /ayuda/{tema}
    defaults: { _controller: CursoSymfonyMainBundle:Default:ayuda }

curso_symfony_main_info:
    path:     /nosotros/{nombre}/{apellidos}/{nacimiento}
    defaults: { _controller: CursoSymfonyMainBundle:Info:nosotros, nombre::Fernando, apellidos::Meneses, nacimiento::Spain }

